### ISSUE TITLE
Questions about data processing

### ISSUE THREAD

**Issue by ChujieXu** [thuml/Corrformer#1]
Hi authors, thank you very much for your very interesting open source work.

when i run the following code

bash ./scripts/Global_Temp/Corrformer.sh

I found that at the following code

https://github.com/thuml/Corrformer/blob/aaa0a88616cf3bcd5d2d27308cec924bf39d735c/models/Corrformer.py#L141-L142

Before enc_embedding and encoder, the code will change the input x_enc from [1, 48, 3850] dimensions to [350, 48, 11]. I don't quite understand why?
I can understand that 3850 is the number of stations and 48 is the length of time, but why should it become 350? Will this aggregate data from several stations together? What does this variable node_num represent?

Looking forward to your answer, thank you.

**Comment by wuhaixu2016** [comment]
Hi, we adopt the hierarchical neighborhood clustering (Eq (4) of the paper) to reorganize the weather stations. And the 3850 stations are clustered in 3 scales, that is 7, 50 and 11. Thus, we aggregate data from several stations together since these stations come from a local region.
