### ISSUE TITLE
多尺度树结构构建问题

### ISSUE THREAD

**Issue by dushik** [thuml/Corrformer#10]
作者您好！在使用层次领域聚类算法应用站点位置信息构建多尺度数时，尺度为0时，叶子节点为站点，能够理解使用kmeans算法对叶子节点聚类再根据聚类结果对站点排序；那尺度为1时，如何使用kmeans算法聚类？还是应用在所有站点数据上吗？还是应用在尺度为0的聚类结果至上，根据尺度为0时聚类得到的簇，计算每个簇地理位置的平均值，然后再对这些平均值应用kmeans？作者能否清楚解答一下使用聚类算法对站点排序这块的内容，不胜感激！

**Comment by hangzhou188** [comment]
尺度为1时，应当应用在尺度为0时每个簇地理位置的均值上，对这些均值应用K-Means

**Comment by wuhaixu2016** [comment]
您好，感谢关注，这个问题请见我们在附录中的说明，对应Supplementary information的Algorithm 1
https://static-content.springer.com/esm/art%3A10.1038%2Fs42256-023-00667-9/MediaObjects/42256_2023_667_MOESM1_ESM.pdf
