### ISSUE TITLE
将程序移植到一个Benchmark后的产生问题

### ISSUE THREAD

**Issue by Zhen-Bu-Chuo** [thuml/Corrformer#13]
我在把程序移植到BasicTS的benchmark之后在训练过程中产生了反向传播梯度为NAN的情况，请问您之前有遇到过此类情况吗

**Comment by wuhaixu2016** [comment]
您好，感谢使用，我们实验中没有遇到过这个问题。

我不太熟悉BasicTS这个框架，不过需要注意Corrformer的设计依赖于我们学习到的树形结构，如果想做spatiotemporal建模任务的话，需要先将traffic的节点顺序进行预处理。
