### ISSUE TITLE
Questions about the dataset

### ISSUE THREAD

**Issue by ChujieXu** [thuml/Corrformer#2]
Many thanks to the authors for opening up the source code and dataset.

I have a question about the dataset. In the Global wind/temp dataset, stations_sorted.npy seems to have sorted the stations. The tree structure of the network is also built directly based on the sorted stations. So if I were to apply Corrformer to other datasets, in what order should stations be fed into the network? Or what preprocessing do I need to do with other station datasets? I really hope to get help from the authors. Thank you very much.

**Comment by wuhaixu2016** [comment]
Hi, thanks for your interests.

As stated in our paper, we adopt the hierarchical neighbourhood clustering (Algorithm 1 of Supplementary Information) to organize the stations.

For your own dataset, you need to find out the multiscale structure of stations firstly. Take the tree structure [S1, S2, S3] as the example. You can just view these stations to a plain sequence with size S1 * S2 * S3.

I think you can get a better understanding after reading this function: https://github.com/thuml/Corrformer/blob/main/layers/Multi_Correlation.py#L292

**Comment by ChujieXu** [comment]
Thank you for your reply, algorithm 1 in the supplementary information solved my confusion.
