### ISSUE TITLE
请问是否可以采用Multi-input-Single-output的预测模型？

### ISSUE THREAD

**Issue by kewang-seu** [thuml/Corrformer#3]
作者您好！请问corrformer是否可以实现多维特征预测单维输出的模式？在参数设置中我看到了'S'、'MS'和'M'三种模型，但在数据加载中并没有看到其应用，仅发现了一个S_station的模式。

**Comment by wuhaixu2016** [comment]
您好，可以实现多维预测单一维度，您可以改写data loader实现，只需要将待预测的维度放在最后一个变量上即可，对应需要改动这一行代码：https://github.com/thuml/Corrformer/blob/main/data_provider/data_loader.py#L49C41-L49C47
