### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by FKK-kun** [thuml/Corrformer#4]
May I ask the author, is the data needed for Demo still open? At present, the link you provided can not be opened

**Comment by wuhaixu2016** [comment]
Sorry for the inconvenience. Since I have graduated from Tsinghua in June, the school deleted my sharing repo. I will re-upload the dataset and pretrain models soon.
In these days, you can obtain the above mentioned stuffs from CodeOcean: https://codeocean.com/capsule/0341365/tree/v1

**Comment by FKK-kun** [comment]
Thank you very much for your reply！

**Comment by Joyce0-0** [comment]
Hello author, when can the data be uploaded? Thank you.

**Comment by FKK-kun** [comment]
Is the global_wind_hourly_data  the wind speed data? His value seems to be relatively large, in the range of 40-140？Has it undergone any treatment

**Comment by leonzfa** [comment]
I can't download the data neither. It says "Sorry, but the requested page could not be found." Could you please upload the data to Baidu Cloud or Google Drive? Thanks.

**Comment by wuhaixu2016** [comment]
Hi, you can find the dataset from codeocean. Both datasets and pretrained models are under the ./data folder.

**Comment by leonzfa** [comment]
> Hi, you can find the dataset from codeocean. Both datasets and pretrained models are under the ./data folder.

OK. I saw it. Thanks.
