### ISSUE TITLE
About Tree-based multi-scale structure

### ISSUE THREAD

**Issue by ningque-t** [thuml/Corrformer#5]
How to do '**the tree is built on the geographical locations of stations by hierarchical neighbourhood clusterin**g'?
In this part, is the order of nodes divided according to the clustering results before the data is input?
Not reflected in the code

Thanks and regards

**Comment by wuhaixu2016** [comment]
Hi, thanks for your interests.
You need to change the node order according to the clustering before input. The provided datasets: Global Temp & Wind have already been re-ordered.

**Comment by ningque-t** [comment]
Thank you very much for your reply！
