### ISSUE TITLE
anyone know how much GPU memory  needed?

### ISSUE THREAD

**Issue by ChaosTong** [thuml/Corrformer#7]
Try using the script located at ‘scripts/Global_Temp/Corrformer.sh’ to train model 48 for predicting 24. How much GPU memory is required? And do you have any solutions to reduce it? 16GB is insufficient.

**Comment by ChaosTong** [comment]
i read the paper and i got it.

**Comment by Duanyy1** [comment]
Could you tell me how long it took you to train the model with what configuration? and it took me much time to train the model with the H800
