### ISSUE TITLE
about the data preprocess code

### ISSUE THREAD

**Issue by Mindywu012** [thuml/Corrformer#8]
Hi, authors.
Can you release the code for data preprocess or how you use the blank series to train the model?
thank you!

**Comment by wuhaixu2016** [comment]
Hi,
We have included the implementation details in supplementary material, including data downloading and preprocessing.
We do not use blank series to train the model. The blank series is just a placeholder to ensure the tree structure. In practice, the blank series is a very small percentage of the whole dataset (smaller than 1% for global and regional datasets)
