### ISSUE TITLE
消融实验中tree结构

### ISSUE THREAD

**Issue by okaygogo** [thuml/Corrformer#9]
您好，在文章中消融实验部分，您是如何实现消除tree结构呢？
  通过修改参数（--node_num    --node_list）实现吗？
  还是修改encoder - decoder等部分呢？
期待您的回复。

**Comment by wuhaixu2016** [comment]
您好，可以将这个参数（https://github.com/thuml/Corrformer/blob/main/scripts/Global_Temp/Corrformer.sh#L25）设置为350，来消除corrformer中的层次结构
